### ISSUE TITLE
Wrong method being written out in docs from programgen

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-dotnet#12]
### What happened?

I don't have a complete list, but there are a couple of occasions where the Azure Classic provider docs reference the `getclientconfig` method. In the C# examples, it says to use the following method: `Azure.Core.GetClientConfig.Invoke();` but that doesn't exist. It should be `Azure.Core.GetClientConfig.InvokeAsync();`.

### Steps to reproduce

https://www.pulumi.com/registry/packages/azure/api-docs/core/getclientconfig/#example-usage
https://www.pulumi.com/registry/packages/azure/api-docs/compute/diskencryptionset/#example-usage 

(both C#)

### Expected Behavior

Method should be `Azure.Core.GetClientConfig.InvokeAsync();`

### Actual Behavior

It shows as: `Azure.Core.GetClientConfig.Invoke();`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
`Invoke` exists now, closing as done: https://github.com/pulumi/pulumi-azure/blob/be9e0084ad876e70aeed2a9ffb4e5234dd6e3b5a/sdk/dotnet/Core/GetClientConfig.cs#L61
