### ISSUE TITLE
Secrets passed to nested provider config properties by C# programs are stored unencrypted 

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-dotnet#142]
### What happened?

Noticing that passing secrets to explicit provider configuration results in the secret material stored un-encrypted in the statefile when nested properties are used from a C# program. The same TypeScript program does not have the issue.

### Expected Behavior

Secrets are kept secret.

### Steps to reproduce

See TestSecretsInExplicitProvider in pulumi-docker. This https://github.com/pulumi/pulumi-docker/pull/644 adds a TypeScript reference passing version. The essence of the test is to look for secrets using `pulumi stack export`.

Also reproduces on pulumi-gcp v6.56.0 so the issue is not docker-specific.

```csharp
using Pulumi;
using Pulumi.Gcp;
using Pulumi.Gcp.Storage;
using System.Collections.Generic;

return await Deployment.RunAsync(() =>
{
    var scopes = new Pulumi.InputList<string>();
    scopes.Add(Output.CreateSecret("secret-scope"));

    var prov = new Provider("my-provider", new ProviderArgs
    {
        Project = "pulumi-development",
        Scopes = scopes
    });

    return new Dictionary<string, object?>{};
});
```

### Output of `pulumi about`

```
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  docker-640 -> /Users/t0yv0/code/pulumi-docker/examples/test-secrets-in-explicit-provider/csharp/bin/Debug/net6.0/docker-640.dll


Build succeeded.

    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.15

'dotnet build -nologo .' completed successfully
CLI          
Version      3.67.1-dev.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.2.1
dotnet  unknown
random  4.13.1

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in dotnet: executable='/Users/t0yv0/.nix-profile/bin/dotnet' version='6.0.403'

Current Stack: t0yv0/docker-640/dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::docker-640::pulumi:pulumi:Stack::docker-640-dev
pulumi:providers:docker                     urn:pulumi:dev::docker-640::pulumi:providers:docker::provider-with-sensitive-address
pulumi:providers:docker                     urn:pulumi:dev::docker-640::pulumi:providers:docker::provider-with-password
pulumi:providers:random                     urn:pulumi:dev::docker-640::pulumi:providers:random::default_4_13_1
random:index/randomPassword:RandomPassword  urn:pulumi:dev::docker-640::random:index/randomPassword:RandomPassword::password
pulumi:providers:docker                     urn:pulumi:dev::docker-640::pulumi:providers:docker::provider-with-random-sensitive-username


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME           VERSION
Pulumi         3.54.1
Pulumi.Docker  4.2.1
Pulumi.Random  4.13.1

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

```

### Additional context

The issue originated from investigating pulumi/pulumi-docker#640 .

Unlike TypeScript, .NET SDK gen proactively marks Password with Output.CreateSecret because it is a secret property in the schema. This is possibly unnecessary. See this [request](https://github.com/pulumi/home/issues/2812) for clarifying the design responsibilities between SDK Gen, engine and providers.

More to the point, unlike TypeScript, .NET program ends up encoding secret data as a nested secret inside a JSON-in-proto encoding. Related issue: https://github.com/pulumi/pulumi/issues/12773  - notice how password is sent in the `news` section:

```
{
  "method": "/pulumirpc.ResourceProvider/CheckConfig",
  "request": {
    "urn": "urn:pulumi:dev::docker-640::pulumi:providers:docker::docker",
    "olds": {
      "host": "ssh://user@remote-host:22",
      "registryAuth": "[{\"address\":\"somewhere.org\",\"password\":\"some-password\",\"username\":\"some-user\"}]",
      "version": "4.2.1"
    },
    "news": {
      "host": "ssh://user@remote-host:22",
      "registryAuth": "[ { \"address\": \"somewhere.org\", \"password\": { \"4dabf18193072939515e22adb298388d\": \"1b47061264138c4ac30d75fd1eb44270\", \"value\": \"some-password\" }, \"username\": \"some-user\" } ]",
      "version": "4.2.1"
    }
  },
```

This currently defeats the expectations of both the engine and the bridge. 

The bridge expects that since it responded with "acceptSecrets: false" to the engine, it will not be sent program-level secret inputs, and definitely not as double-encoded secrets inside JSON-in-proto. To accommodate current C# behavior it started ignoring these secrets since https://github.com/pulumi/pulumi-terraform-bridge/pull/1140 - basically normalizing these secrets to their underlying value.

Now unfortunately simply ignoring them is insufficient to keep the material encrypted. For top-level secret properties, the bridge expects the engine to track secretes for program-defined secrets through black-box resources, which goes hand in hand with "acceptSecrets: false". Based on "acceptSecrets: false", the expectation is that the engine will not send secrets to Configure/CheckConfig inputs but instead mark matching output properties as secret automatically. This is *not* happening in the case of C# programs with nested secrets in provider configuration.

The possible alternative fixes here are:

- edit C# SDK or C# SDK generator to do the same thing as TypeScript SDK; do not wrap schema properties with Output.Secret and do not encode nested secrets inside JSON-in-proto 

- edit the bridge to assume additional responsibility for secrets originating from the program; recognize nested JSON-in-proto secrets and copy heuristics from the engine to propagate secret bits to matching outputs by path or value

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
InputList does behave a bit odd, I suspect a secret tracking bit is probably being lost in there somewhere,

**Comment by t0yv0** [comment]
I'm pretty sure this serial form is where its' lost:

```
"[ { \"address\": \"somewhere.org\", \"password\": { \"4dabf18193072939515e22adb298388d\": \"1b47061264138c4ac30d75fd1eb44270\", \"value\": \"some-password\" }, \"username\": \"some-user\" } ]",
```

The plumbing doesn't expect secret markers *inside* JSON, so most other systems think `1b47061264138c4ac30d75fd1eb44270` is a map key now not a secret marker.

**Comment by justinvp** [comment]
> The plumbing doesn't expect secret markers _inside_ JSON, so most other systems think `1b47061264138c4ac30d75fd1eb44270` is a map key now not a secret marker.

Yeah, it looks like this is a bug in the way the .NET SDK serializes values for provider inputs. Non-string values need to be serialized to JSONs and sent as a JSON string. We shouldn't be keeping `4dabf18193072939515e22adb298388d` and `1b47061264138c4ac30d75fd1eb44270` in the nested JSON. Based on the way the protocol works today, we'd have to strip those when serializing to JSON and mark the whole top-level input as secret.

**Comment by t0yv0** [comment]
> Based on the way the protocol works today, we'd have to strip those when serializing to JSON and mark the whole top-level input as secret.

I can confirm that this should work with how the bridge is implemented. That'd let us uncomment the skipped tests in docker.

**Comment by Frassle** [comment]
> Yeah, it looks like this is a bug in the way the .NET SDK serializes values for provider inputs. Non-string values need to be serialized to JSONs and sent as a JSON string.

That doesn't line up with my understanding of the RPC protocol. Marshal/Unmarshal should handle nested secret values just fine generally.

Further the engines supposed to strip all secrets from provider config anyway (because we pass config before calling Configure to see if the provider supports secrets or not) so regardless of what C# sends for the properties tfbridge shouldn't be seeing any secrets. This appears to be what's broken, I'm seeing secret signatures in the inputs for CheckConfig using the GCP example above.

**Comment by Frassle** [comment]
Ah, ok debug output was a bit confusing but tracked it down.
dotnet has the option to mark resource inputs as "json" and the scopes property for GCP is an example of that. When "json" is set the secret object is sent as a JSON string, rather than as a string of the value, wrapped in a secret object.

**Comment by mikhailshilkov** [comment]
Is there a postmortem on this one?

**Comment by Frassle** [comment]
Probably should be but technically not a regression, this has always been broken.
