### ISSUE TITLE
Pulumi program hangs when resource transformation throws an exception

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi-dotnet#174]
### What happened?

When using a `ResourceTransformation` as a stack option and that transform throws an exception, `pulumi preview` and `pulumi up` hang forever. 

### Expected Behavior

`pulumi preview` and `pulumi up` should not hang, instead, the transformation should catch errors and show them to users.

### Steps to reproduce

The following C# Pulumi program demonstrates the problem:
```cs
using System.Threading.Tasks;
using Pulumi;
using Pulumi.Aws.S3;

class MyStack : Stack
{
    static StackOptions Options() => new StackOptions()
    {
        ResourceTransformations = { FailingTransform() } 
    };

    public MyStack() : base(Options())
    {
        var bucket = new Bucket("my-bucket");
    }

    static ResourceTransformation FailingTransform() 
    {
        return args => 
        {
            throw new System.Exception("Boom!");
            return null;
        };
    }
}


class Program
{
    static Task<int> Main() => Deployment.RunAsync<MyStack>();
}
```

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.0.2
dotnet  unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by darthkurak** [comment]
Is there a chance to fix that?

**Comment by darthkurak** [comment]
@Zaid-Ajaj I tried pre-release version with this fix, and it seems that it doesn't work when using Deployment.TestAsync (however it works with Deployment.RunAsync)

**Comment by Zaid-Ajaj** [comment]
@darthkurak Can you maybe open a new issue with repro code if possible? 🙏

**Comment by darthkurak** [comment]
Don't have obvious repro code, because it failed in my bigger codebase. But I think you may basically throw some exceptions in transformation when running Stack inside from Deployment.TestAsync, something like

Deployment.TestAsync(p => new SomeStackThatHaveTransformations() ) - and you should have a similar effect - The test should hang forever.
