### ISSUE TITLE
Update `Grpc.AspNetCore.Server.Reflection` to a more recent version

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-dotnet#218]
Customer has pointed out that we're on [v2.37.0 of this nuget package](https://github.com/pulumi/pulumi-dotnet/blob/main/sdk/Pulumi/Pulumi.csproj#L35) and it's throwing alerts in their static analysis tooling.

The version we're using is dated 20/04/2021 so it is nearly [3 years old now ](https://www.nuget.org/packages/Grpc.AspNetCore.Server.Reflection/2.37.0#versions-body-tab)

![DependencyTree](https://github.com/pulumi/pulumi-dotnet/assets/109047/c5e8e384-5f69-49d4-987e-cb71f9a59e9b)
![Vulnerability](https://github.com/pulumi/pulumi-dotnet/assets/109047/18efb036-e28d-44fe-af5e-44e2d221a009)

**Comment by ttvrdon** [comment]
@pierskarsenbarg Thanks Pier for really quick action with this fix. I reviewed the PR and this will not help...
Vulnerability was fixed in version 2.59.0

**Comment by Frassle** [comment]
That's going to be trickier because it drops support for dotnet 3. I'll talk to the team about what we can do here.

**Comment by mikhailshilkov** [comment]
@Frassle Why is dropping dotnet 3 a problem? It's not a supported version for 1.5 years, right?

**Comment by Frassle** [comment]
> Why is dropping dotnet 3 a problem?

We broke a load of downstream provider builds last time, it was technically a few months out of support even then. It _should_ be fine, but I haven't been able to get anyone to confirm it's ok to make this break change.
