### ISSUE TITLE
NullReferenceException from InputList implicit operator

### ISSUE THREAD

**Issue by thecodetinker** [pulumi/pulumi-dotnet#326]
### What happened?

Setting an `InputList<string>` with the `{ "Foo" }` syntax compiles fine, but results in a runtime `NullReferenceException`.

This is a horrible time-consuming bug because it's just a weird runtime issue. Of all the things we could think of that caused the failure in our pipeline, just setting the `InputList` on the args with this syntax was a long way down!

### Example

Here is an NUnit test to reproduce the problem. `AddSingleString` and `AddList` pass. 

However, `AddListNewSyntax` fails with `System.NullReferenceException : Object reference not set to an instance of an object.`.

NB: `GetValueAsync` is courtesy of your [testing post](https://www.pulumi.com/docs/using-pulumi/testing/unit/#add-mocks).

```csharp
internal class OperatorTests
{
    [Test]
    public async Task AddSingleString()
    {
        var args = new MyResourceArgs
        {
            MyList = "Hello"
        };

        var result = await GetFirstValue(args.MyList);

        result.Should().Be("Hello");
    }

    [Test]
    public async Task AddList()
    {
        var args = new MyResourceArgs
        {
            MyList = new InputList<string>() { "Hello" }
        };

        var result = await GetFirstValue(args.MyList);

        result.Should().Be("Hello");
    }

    [Test]
    public async Task AddListNewSyntax()
    {
        var args = new MyResourceArgs
        {
            MyList = { "Hello" }
        };

        var result = await GetFirstValue(args.MyList);

        result.Should().Be("Hello");
    }

    private static async Task<string> GetFirstValue(InputList<string> inputList)
    {
        var resultEnumerator = inputList.GetAsyncEnumerator(new CancellationTokenSource().Token);

        await resultEnumerator.MoveNextAsync();
        return await resultEnumerator.Current.ToOutput().GetValueAsync();
    }
}

internal class MyResourceArgs
{
    public InputList<string> MyList { get; init; } = null!;
}
```

### Output of `pulumi about`

This is in the C# library version `3.66.1`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
@thecodetinker So looking into this, I am not sure there is something wrong with the Pulumi SDK itself, it looks like that to be able to use the list initializer using the syntax `= { <elem> }` you need your property to be initialized (to be non-null)
```diff
internal class MyResourceArgs
{
-    public InputList<string> MyList { get; init; } = null!;
+    public InputList<string> MyList { get; init; } = new();
}
```
I think this is because the syntax:
```cs
var args = new MyResourceArgs
{
    MyList = { "Hello" }
};
```
Translates to
```cs
var args = new MyResourceArgs();
args.MyList.Add("Hello");
```
Which causes the `NullReferenceException` since we are calling `Add` on `MyList` which is null.

That said, I believe we generate our C# provider SDKs with `= null!` which we need to fix

**Comment by Zaid-Ajaj** [comment]
Another question: did you encounter this error using an `Args` class that we generated or is it a manually written class (e.g. for component resources)?

**Comment by thecodetinker** [comment]
Ok crikey you're right. It happens if the arg is a regular `List<string>`, not just `InputList<string>`, so it must be an underlying .Net thing. It was indeed one of our Args classes I believe, but it seems like we should adopt your convention here to make sure this doesn't happen.

So I think this is not a pulumi issue after all, just a regular horrible .Net behaviour. Sorry to trouble you, and thanks for looking at it!

**Comment by Zaid-Ajaj** [comment]
@thecodetinker No worries at all. We are here to help 😄
