### ISSUE TITLE
Debugging non-C# .NET projects (F#, VB.NET) fails due to missing `.csproj` file

### ISSUE THREAD

**Issue by cagyirey** [pulumi/pulumi-dotnet#352]
### What happened?

**Expectation:** When using `--debugger-attach` or VS Code to debug a non-C# .NET project, `pulumi preview`/`up` should build and attach to the target project.

**What happens instead:** it exits with the following message, indicating a failure to find a `.csproj` file:

```
[truncated]
    pulumi:pulumi:Stack MyStack  Build succeeded.
    pulumi:pulumi:Stack MyStack      0 Warning(s)
    pulumi:pulumi:Stack MyStack  
    pulumi:pulumi:Stack MyStack  Time Elapsed 00:00:01.33
    pulumi:pulumi:Stack MyStack  'dotnet build -nologo MyProject.fsproj' completed successfully
    pulumi:pulumi:Stack MyStack  error: failed to find .csproj file, and could not start debugging
    pulumi:pulumi:Stack MyStack  1 error
Diagnostics:
  pulumi:pulumi:Stack (MyStack):
    error: failed to find .csproj file, and could not start debugging
```

When debugging an F# project (`.fsproj`) or VB.NET project (`.vbproj`), this file will never exist. This is because only `.csproj` files are searched for in [`pulumi-language-dotnet/main.go`](https://github.com/pulumi/pulumi-dotnet/blob/01e6b9c75303c4254bf2e24cb4806ff9291a2c8f/pulumi-language-dotnet/main.go#L581). This should be changed to also search for `.fsproj` and `.vbproj` files.

Additionally, the behaviour of searching for a project file is brittle. It does not respect the project file declared in `Pulumi.yaml` project settings:

```yaml
name: MyPulumiFSharpProject
runtime: dotnet
main: MyProject.fsproj 
```

Even with the above, the Go driver still uses the first `.csproj` found. If there are more than one `.csproj` (or a `.csproj` and `.fsproj`) in the same folder, the meaning of the arguments to `dotnet build` in [main.go line 567](https://github.com/pulumi/pulumi-dotnet/blob/main/pulumi-language-dotnet/main.go#L567) become ambiguous:

```
Diagnostics:
  pulumi:pulumi:Stack (MyStack):
    Found more than one project in `/workspace/MyProject`. Specify which one to use.
```

**Solution:** When debugging Pulumi .NET projects, the `name` property of the `Pulumi.yaml` project file should be respected, and its value should be added to the arguments passed to `dotnet build`. Per the docs:

> For .NET projects, `main` can point to a .NET project file (e.g., `example.csproj`) and the file will be passed to `dotnet run`.

### Example

1. Create an F# project with `dotnet new classlib -lang "f#" -o MyPulumiProject` and import NuGet dependencies for Pulumi.

2. Install the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=pulumi.pulumi-vscode-tools)

3. Create a debugging profile. My `launch.json`:
```
    {
      "type": "pulumi",
      "request": "launch",
      "name": "pulumi preview",
      "command": "preview",
      "workDir": "${workspaceFolder}/"
      
    }
```

4. Launch and observe the debugging window.

5. The Go driver searches the child directories of the project folder in order to find a `.csproj`. This name is used to debug the corresponding `.dll` file. To confirm that [main.go line 581 is the culprit](https://github.com/pulumi/pulumi-dotnet/blob/01e6b9c75303c4254bf2e24cb4806ff9291a2c8f/pulumi-language-dotnet/main.go#L581C3-L581C62), copy `MyPulumiProject.fsproj` to `./bin/MyPulumiProject.csproj` and launch the debugger again. It works!

### Output of `pulumi about`
```
CLI          
Version      3.133.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
language  dotnet      unknown
resource  kubernetes  4.18.1
resource  random      4.16.5

Host     
OS       darwin
Version  15.0
Arch     arm64

This project is written in dotnet: executable='/opt/homebrew/bin/dotnet' version='8.0.301'
[truncated]
Backend        
Name           pulumi.com
[truncated]
Token type     personal

Dependencies:
NAME                                                   VERSION
Ben.Demystifier                                        0.4.1
FSharp.Core                                            8.0.400
Glob                                                   1.1.9
Google.Protobuf                                        3.28.2
Grpc.AspNetCore.Server                                 2.66.0
Grpc.AspNetCore.Server.Reflection                      2.66.0
Grpc.Core.Api                                          2.66.0
Grpc.Net.Client                                        2.66.0
Grpc.Net.Common                                        2.66.0
Grpc.Reflection                                        2.66.0
Microsoft.Extensions.DependencyInjection               8.0.0
Microsoft.Extensions.DependencyInjection.Abstractions  8.0.1
Microsoft.Extensions.Logging                           8.0.0
Microsoft.Extensions.Logging.Abstractions              8.0.1
Microsoft.Extensions.Options                           8.0.2
Microsoft.Extensions.Primitives                        8.0.0
Newtonsoft.Json                                        13.0.3
OneOf                                                  3.0.271
Pulumi                                                 3.67.1
Pulumi.FSharp                                          3.67.1
Pulumi.FSharp.Core                                     3.1.6
Pulumi.FSharp.Kubernetes                               4.16.0
Pulumi.FSharp.Random                                   4.16.3
Pulumi.Kubernetes                                      4.18.1
Pulumi.Protobuf                                        3.27.3
Pulumi.Random                                          4.16.5
Semver                                                 2.3.0
Serilog                                                4.0.1
Serilog.Extensions.Logging                             8.0.0
Serilog.Sinks.Console                                  6.0.0
System.Collections.Immutable                           8.0.0
System.Reflection.Metadata                             8.0.0
YamlConvert                                            2.1.1
YamlDotNet                                             15.1.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the detailed issue, @cagyirey!
