### ISSUE TITLE
warning: failed to get plugin info for language plugin client

### ISSUE THREAD

**Issue by johnsonp57** [pulumi/pulumi-dotnet#369]
### What happened?

Since this change was committed to Pulumi CLI (https://github.com/pulumi/pulumi/pull/17216/), we are seeing a warning emitted on every run.

warning: failed to get plugin info for language plugin client:

Reverting to Pulumi version prior to 1.32 does not show the warning

### Example

Run Pulumi on any stack using the dotnet runtime and Pulumi CLI > 1.32 and you will see this warning

warning: failed to get plugin info for language plugin client:

### Output of `pulumi about`

CLI
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME                 VERSION
resource  azure-native         2.64.0
resource  azuread              5.53.4
resource  command              0.10.0
resource  crds                 2.8.0
resource  crds.aadpodidentity  2.8.2
language  dotnet               unknown
resource  kubernetes           4.18.1
resource  random               4.16.6
resource  time                 0.1.0

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='8.0.400'

Backend
Name           ***
URL            file://~
User           ***
Organizations
Token type     personal

Dependencies:
NAME                                                            VERSION
Azure.ResourceManager                                           1.13.0
CommandLineParser                                               2.9.1
Ict.Configuration                                               6.0.3
IPNetwork2                                                      3.0.667
Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers  0.4.421302
Microsoft.Graph                                                 5.58.0
Newtonsoft.Json                                                 13.0.3
Pulumi                                                          3.67.1
Pulumi.Automation                                               3.67.1
Pulumi.AzureNative                                              2.64.0
Pulumi.Kubernetes                                               4.18.1
Pulumiverse.Time                                                0.1.0
Serilog                                                         3.1.1
Azure.Identity                                                  1.12.0
Azure.ResourceManager                                           1.13.0
Azure.ResourceManager.Network                                   1.9.0
Azure.Security.KeyVault.Secrets                                 4.6.0
Pulumi                                                          3.67.1
Pulumi.Automation                                               3.67.1
Pulumi.AzureAD                                                  5.53.4
Pulumi.AzureNative                                              2.64.0
Pulumi.Random                                                   4.16.6
Serilog                                                         3.1.1
Serilog.Expressions                                             4.0.1-dev-00151
Azure.ResourceManager.ContainerService                          1.2.2
Azure.ResourceManager.Network                                   1.9.0
CommandLineParser                                               2.9.1
Ict.AzureNative                                                 7.1.18
Ict.Configuration                                               6.0.3
Ict.Kubernetes                                                  3.0.1
IPNetwork2                                                      3.0.667
Newtonsoft.Json                                                 13.0.3
Pulumi                                                          3.67.1
Pulumi.Automation                                               3.67.1
Pulumi.AzureNative                                              2.64.0
Pulumi.Crds                                                     1.0.13
Pulumi.Crds.AadPodIdentity                                      1.0.13
Pulumi.Kubernetes                                               4.18.1
Serilog                                                         3.1.1
Azure.ResourceManager                                           1.13.0
Ict.AzureNative                                                 7.1.18
Ict.Kubernetes                                                  3.0.1
Pulumi                                                          3.67.1
Pulumi.Automation                                               3.67.1
Pulumi.AzureAD                                                  5.53.4
Pulumi.AzureNative                                              2.64.0
Pulumi.Crds                                                     1.0.13
Pulumi.Crds.AadPodIdentity                                      1.0.13
Pulumi.Kubernetes                                               4.18.1
Pulumi.Random                                                   4.16.6
Serilog                                                         3.1.1
Azure.ResourceManager                                           1.13.0
Ict.AzureNative                                                 7.1.18
Ict.Kubernetes                                                  3.0.1
Pulumi                                                          3.67.1
Pulumi.Automation                                               3.67.1
Pulumi.AzureNative                                              2.64.0
Pulumi.Crds                                                     1.0.13
Pulumi.Crds.AadPodIdentity                                      1.0.13
Pulumi.Kubernetes                                               4.18.1
Microsoft.SqlServer.DacFx                                       162.4.92
Serilog                                                         3.1.1

Pulumi locates its logs in C:\Users\PETER4~1\AppData\Local\Temp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue, @johnsonp57, and sorry for the trouble!

I've been able to reproduce this with an Automation API inline program. The problem is because https://github.com/pulumi/pulumi-dotnet/blob/b03530027118e9305c2b69be37f88a70ceb81900/sdk/Pulumi.Automation/Runtime/LanguageRuntimeService.cs#L13 doesn't implement `GetPluginInfo`.

We should fix the .NET SDK to do that. We probably should also fix the CLI to be more lenient when `GetPluginInfo` isn't implemented, and not emit a warning. (Instead, we could still log a message, but one that won't show up by default in the output).

**Comment by johnsonp57** [comment]
Thanks @justinvp for looking at this - do you know when the PR might make it to release?

**Comment by justinvp** [comment]
@johnsonp57, apologies for the delay! This has been released in v3.70.0 of the SDK.
