### ISSUE TITLE
Consider C# Idiomatic API

### ISSUE THREAD

**Issue by nbarnwell** [pulumi/pulumi-dotnet#45]
Currently it's a bit weird and unintuitive that in the C# style, the variables are just magically captured for certain types. This is a significant cheese migration when one comes to it fresh, having been told "it's just C#".

My assumption when I came to it was that I'd implement/inherit a class (e.g. the current `Stack` class), and this would require me to implement/override a method (rather than using the constructor), that perhaps returned `IEnumerable<CustomResource>`. That would still allow the setting of `Output` values etc, but would allow easier unit testing, and even better, rather than capturing variables using magic, would allow us to use C# `yield return new SecurityGroup(...)'` style.

It would seem possible to introduce this style as an option to start with.

Example:
```
// This is an example, using https://github.com/pulumi/examples/blob/master/aws-cs-webserver/WebServerStack.cs as inspiration.

using Pulumi;
using Pulumi.Aws;
using Pulumi.Aws.Ec2;
using Pulumi.Aws.Ec2.Inputs;
using Pulumi.Aws.Inputs;

class WebServerStack : Stack
{
    public IEnumerable<CustomResource> GetResources()
    {
        yield return Output.Create(GetAmi.InvokeAsync(new GetAmiArgs
        {
            MostRecent = true,
            Owners = {"137112412989"},
            Filters = {new GetAmiFilterArgs {Name = "name", Values = {"amzn-ami-hvm-*"}}}
        }));

        var group = new SecurityGroup("web-secgrp", new SecurityGroupArgs
        {
            Description = "Enable HTTP access",
            Ingress =
            {
                new SecurityGroupIngressArgs
                {
                    Protocol = "tcp",
                    FromPort = 80,
                    ToPort = 80,
                    CidrBlocks = {"0.0.0.0/0"}
                }
            }
        });
        yield return group;

        var userData = @"
#!/bin/bash
echo ""Hello, World!"" > index.html
nohup python -m SimpleHTTPServer 80 &
";

        var server = new Instance("web-server-www", new InstanceArgs
        {
            InstanceType = Size,
            VpcSecurityGroupIds = {group.Id},
            UserData = userData,
            Ami = ami.Apply(a => a.Id)
        });
        yield return server;

        this.PublicIp = server.PublicIp;
        this.PublicDns = server.PublicDns;
    }

    [Output] public Output<string> PublicIp { get; set; }

    [Output] public Output<string> PublicDns { get; set; }

    private const string Size = "t2.micro";
}
```

**Comment by dferretti** [comment]
Just throwing out some ideas, but a syntax sort of like this could help force the developer to register the resources:
```c#
class MyStack : Stack
{
    public void GetResources(Manifest manifest) // name TBD
    {
        manifest.Add("security-group", new SecurityGroupArgs { ... }); // returns instance of SecurityGroup

        var bucket = manifest.Add("bucket", new BucketArgs { ... }); // returns instance of Bucket
        manifest.Add("something-else", new SomethingArgs { Bucket = bucket.Name });
    }
}
```

And the c# resource providers would all contain `internal` constructors for resources. So users would have no way of declaring an orphaned resource, but instead would be forced to go through the manifest.

And to get that `manifest.Add` to work, it would need some work but I think it could work with generics where we have say `Bucket : CustomResource<BucketArgs>` so `manifest.Add` could figure out the `T` / `TArgs` to make it easy to consume.

Or another way, the resource provider could add extension methods like `Bucket AddBucket(this Manifest m, BucketArgs args)`

**Comment by asalvo** [comment]
I came across this issue while searching for something else, but wanted to echo the OP. Yes, we get to use C#, but it's been a challenge to wrap my head around how Pulumi expects the C# to be written.

**Comment by nbarnwell** [comment]
This is never going to happen so I'm closing it.
