### ISSUE TITLE
Support authoring multi-language components in .NET

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-dotnet#46]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

pulumi/pulumi#5485 adds support for using multi-language components from .NET. This issue tracks being able to author multi-language components in .NET.

**Comment by NatElkins** [comment]
Interested in this but probably won't work on it myself.   That said, here's a relevant comment from Slack:

<img width="670" alt="image" src="https://github.com/pulumi/pulumi-dotnet/assets/1795462/da7ca018-9404-4321-a795-76b9b32a9622">


> The smallest necessary fix here probably isn't that big, just adding Construct/Call methods to https://github.com/pulumi/pulumi-dotnet/blob/main/sdk/Pulumi/Provider/Provider.cs which will be a similar shape to what they look like in other languages:
e.g. TypeScript https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/provider/server.ts
That would get C# on par with TypeScript.

**Comment by NatElkins** [comment]
@Frassle Is your comment still valid, that the changes shouldn't be too much and that the link you gave is still the place to get started?

**Comment by Frassle** [comment]
Aye, still accurate.

**Comment by algompluecker** [comment]
I am going to work on this topic. @Frassle have you done any development, yet?

**Comment by jkerken** [comment]
@Frassle This is now implemented as part of #275 , anything else missing?

**Comment by Frassle** [comment]
Nothing else. We're at parity with TS/Python now.
