### ISSUE TITLE
Drop support for .NET 3.1

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-dotnet#74]
We currently support .NET 3.1 and .NET 6.0, but Microsoft no longer supports .NET 3.1 as of December 13, 2022.  We should likely drop support for .NET 3.1 as well, but will need to do so iteratively.  We'll need to ensure that all downstream codegen dependencies etc continue to function as desired after this change.

**Comment by justinvp** [comment]
This has long since been addressed.
